/*
 * This file is generated by jOOQ.
*/
package com.ysu.zyw.tc.demo.dao.jooq.tables.records;


import com.ysu.zyw.tc.demo.dao.jooq.tables.TUiClass;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUiClassRecord extends UpdatableRecordImpl<TUiClassRecord> implements Record7<Long, Integer, Long, BigDecimal, String, String, Timestamp> {

    private static final long serialVersionUID = -1411022086;

    /**
     * Setter for <code>webgen.T_UI_CLASS.PK_CLASS</code>.
     */
    public void setPkClass(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>webgen.T_UI_CLASS.PK_CLASS</code>.
     */
    public Long getPkClass() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>webgen.T_UI_CLASS.DEMO_INT</code>.
     */
    public void setDemoInt(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>webgen.T_UI_CLASS.DEMO_INT</code>.
     */
    public Integer getDemoInt() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>webgen.T_UI_CLASS.DEMO_LONG</code>.
     */
    public void setDemoLong(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>webgen.T_UI_CLASS.DEMO_LONG</code>.
     */
    public Long getDemoLong() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>webgen.T_UI_CLASS.DEMO_BIGDIMAL</code>.
     */
    public void setDemoBigdimal(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>webgen.T_UI_CLASS.DEMO_BIGDIMAL</code>.
     */
    public BigDecimal getDemoBigdimal() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>webgen.T_UI_CLASS.DEMO_STRING</code>.
     */
    public void setDemoString(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>webgen.T_UI_CLASS.DEMO_STRING</code>.
     */
    public String getDemoString() {
        return (String) get(4);
    }

    /**
     * Setter for <code>webgen.T_UI_CLASS.DEMO_BOOLEAN</code>.
     */
    public void setDemoBoolean(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>webgen.T_UI_CLASS.DEMO_BOOLEAN</code>.
     */
    public String getDemoBoolean() {
        return (String) get(5);
    }

    /**
     * Setter for <code>webgen.T_UI_CLASS.DEMO_TIMESTAMP</code>.
     */
    public void setDemoTimestamp(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>webgen.T_UI_CLASS.DEMO_TIMESTAMP</code>.
     */
    public Timestamp getDemoTimestamp() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Integer, Long, BigDecimal, String, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Integer, Long, BigDecimal, String, String, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TUiClass.T_UI_CLASS.PK_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TUiClass.T_UI_CLASS.DEMO_INT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return TUiClass.T_UI_CLASS.DEMO_LONG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return TUiClass.T_UI_CLASS.DEMO_BIGDIMAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TUiClass.T_UI_CLASS.DEMO_STRING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TUiClass.T_UI_CLASS.DEMO_BOOLEAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TUiClass.T_UI_CLASS.DEMO_TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPkClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDemoInt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getDemoLong();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getDemoBigdimal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDemoString();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDemoBoolean();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDemoTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiClassRecord value1(Long value) {
        setPkClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiClassRecord value2(Integer value) {
        setDemoInt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiClassRecord value3(Long value) {
        setDemoLong(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiClassRecord value4(BigDecimal value) {
        setDemoBigdimal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiClassRecord value5(String value) {
        setDemoString(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiClassRecord value6(String value) {
        setDemoBoolean(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiClassRecord value7(Timestamp value) {
        setDemoTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiClassRecord values(Long value1, Integer value2, Long value3, BigDecimal value4, String value5, String value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUiClassRecord
     */
    public TUiClassRecord() {
        super(TUiClass.T_UI_CLASS);
    }

    /**
     * Create a detached, initialised TUiClassRecord
     */
    public TUiClassRecord(Long pkClass, Integer demoInt, Long demoLong, BigDecimal demoBigdimal, String demoString, String demoBoolean, Timestamp demoTimestamp) {
        super(TUiClass.T_UI_CLASS);

        set(0, pkClass);
        set(1, demoInt);
        set(2, demoLong);
        set(3, demoBigdimal);
        set(4, demoString);
        set(5, demoBoolean);
        set(6, demoTimestamp);
    }
}
