/*
 * This file is generated by jOOQ.
*/
package com.ysu.zyw.tc.demo.dao.jooq.tables.records;


import com.ysu.zyw.tc.demo.dao.jooq.tables.TUiPerson;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUiPersonRecord extends UpdatableRecordImpl<TUiPersonRecord> implements Record8<Long, Long, Integer, Long, BigDecimal, String, Boolean, Timestamp> {

    private static final long serialVersionUID = -339207944;

    /**
     * Setter for <code>webgen.T_UI_PERSON.PK_CLASS</code>.
     */
    public void setPkClass(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>webgen.T_UI_PERSON.PK_CLASS</code>.
     */
    public Long getPkClass() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>webgen.T_UI_PERSON.PK_PERSON</code>.
     */
    public void setPkPerson(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>webgen.T_UI_PERSON.PK_PERSON</code>.
     */
    public Long getPkPerson() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>webgen.T_UI_PERSON.DEMO_INT</code>.
     */
    public void setDemoInt(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>webgen.T_UI_PERSON.DEMO_INT</code>.
     */
    public Integer getDemoInt() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>webgen.T_UI_PERSON.DEMO_LONG</code>.
     */
    public void setDemoLong(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>webgen.T_UI_PERSON.DEMO_LONG</code>.
     */
    public Long getDemoLong() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>webgen.T_UI_PERSON.DEMO_BIGDIMAL</code>.
     */
    public void setDemoBigdimal(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>webgen.T_UI_PERSON.DEMO_BIGDIMAL</code>.
     */
    public BigDecimal getDemoBigdimal() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>webgen.T_UI_PERSON.DEMO_STRING</code>.
     */
    public void setDemoString(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>webgen.T_UI_PERSON.DEMO_STRING</code>.
     */
    public String getDemoString() {
        return (String) get(5);
    }

    /**
     * Setter for <code>webgen.T_UI_PERSON.DEMO_BOOLEAN</code>.
     */
    public void setDemoBoolean(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>webgen.T_UI_PERSON.DEMO_BOOLEAN</code>.
     */
    public Boolean getDemoBoolean() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>webgen.T_UI_PERSON.DEMO_TIMESTAMP</code>.
     */
    public void setDemoTimestamp(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>webgen.T_UI_PERSON.DEMO_TIMESTAMP</code>.
     */
    public Timestamp getDemoTimestamp() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Integer, Long, BigDecimal, String, Boolean, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Integer, Long, BigDecimal, String, Boolean, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TUiPerson.T_UI_PERSON.PK_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TUiPerson.T_UI_PERSON.PK_PERSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TUiPerson.T_UI_PERSON.DEMO_INT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return TUiPerson.T_UI_PERSON.DEMO_LONG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return TUiPerson.T_UI_PERSON.DEMO_BIGDIMAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TUiPerson.T_UI_PERSON.DEMO_STRING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return TUiPerson.T_UI_PERSON.DEMO_BOOLEAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TUiPerson.T_UI_PERSON.DEMO_TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPkClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPkPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDemoInt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getDemoLong();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getDemoBigdimal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDemoString();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getDemoBoolean();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getDemoTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiPersonRecord value1(Long value) {
        setPkClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiPersonRecord value2(Long value) {
        setPkPerson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiPersonRecord value3(Integer value) {
        setDemoInt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiPersonRecord value4(Long value) {
        setDemoLong(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiPersonRecord value5(BigDecimal value) {
        setDemoBigdimal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiPersonRecord value6(String value) {
        setDemoString(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiPersonRecord value7(Boolean value) {
        setDemoBoolean(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiPersonRecord value8(Timestamp value) {
        setDemoTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiPersonRecord values(Long value1, Long value2, Integer value3, Long value4, BigDecimal value5, String value6, Boolean value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUiPersonRecord
     */
    public TUiPersonRecord() {
        super(TUiPerson.T_UI_PERSON);
    }

    /**
     * Create a detached, initialised TUiPersonRecord
     */
    public TUiPersonRecord(Long pkClass, Long pkPerson, Integer demoInt, Long demoLong, BigDecimal demoBigdimal, String demoString, Boolean demoBoolean, Timestamp demoTimestamp) {
        super(TUiPerson.T_UI_PERSON);

        set(0, pkClass);
        set(1, pkPerson);
        set(2, demoInt);
        set(3, demoLong);
        set(4, demoBigdimal);
        set(5, demoString);
        set(6, demoBoolean);
        set(7, demoTimestamp);
    }
}
