/*
 * This file is generated by jOOQ.
*/
package com.ysu.zyw.tc.demo.dao.jooq.tables;


import com.ysu.zyw.tc.demo.dao.jooq.Keys;
import com.ysu.zyw.tc.demo.dao.jooq.Webgen;
import com.ysu.zyw.tc.demo.dao.jooq.tables.records.TUiClassRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUiClass extends TableImpl<TUiClassRecord> {

    private static final long serialVersionUID = 1310884839;

    /**
     * The reference instance of <code>webgen.T_UI_CLASS</code>
     */
    public static final TUiClass T_UI_CLASS = new TUiClass();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUiClassRecord> getRecordType() {
        return TUiClassRecord.class;
    }

    /**
     * The column <code>webgen.T_UI_CLASS.PK_CLASS</code>.
     */
    public final TableField<TUiClassRecord, Long> PK_CLASS = createField("PK_CLASS", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>webgen.T_UI_CLASS.DEMO_INT</code>.
     */
    public final TableField<TUiClassRecord, Integer> DEMO_INT = createField("DEMO_INT", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>webgen.T_UI_CLASS.DEMO_LONG</code>.
     */
    public final TableField<TUiClassRecord, Long> DEMO_LONG = createField("DEMO_LONG", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>webgen.T_UI_CLASS.DEMO_BIGDIMAL</code>.
     */
    public final TableField<TUiClassRecord, BigDecimal> DEMO_BIGDIMAL = createField("DEMO_BIGDIMAL", org.jooq.impl.SQLDataType.DECIMAL.precision(6, 2), this, "");

    /**
     * The column <code>webgen.T_UI_CLASS.DEMO_STRING</code>.
     */
    public final TableField<TUiClassRecord, String> DEMO_STRING = createField("DEMO_STRING", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

    /**
     * The column <code>webgen.T_UI_CLASS.DEMO_BOOLEAN</code>.
     */
    public final TableField<TUiClassRecord, String> DEMO_BOOLEAN = createField("DEMO_BOOLEAN", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

    /**
     * The column <code>webgen.T_UI_CLASS.DEMO_TIMESTAMP</code>.
     */
    public final TableField<TUiClassRecord, Timestamp> DEMO_TIMESTAMP = createField("DEMO_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>webgen.T_UI_CLASS</code> table reference
     */
    public TUiClass() {
        this("T_UI_CLASS", null);
    }

    /**
     * Create an aliased <code>webgen.T_UI_CLASS</code> table reference
     */
    public TUiClass(String alias) {
        this(alias, T_UI_CLASS);
    }

    private TUiClass(String alias, Table<TUiClassRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUiClass(String alias, Table<TUiClassRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Webgen.WEBGEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TUiClassRecord> getPrimaryKey() {
        return Keys.KEY_T_UI_CLASS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TUiClassRecord>> getKeys() {
        return Arrays.<UniqueKey<TUiClassRecord>>asList(Keys.KEY_T_UI_CLASS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiClass as(String alias) {
        return new TUiClass(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUiClass rename(String name) {
        return new TUiClass(name, null);
    }
}
