/*
 * This file is generated by jOOQ.
*/
package com.ysu.zyw.tc.demo.dao.jooq.tables;


import com.ysu.zyw.tc.demo.dao.jooq.Keys;
import com.ysu.zyw.tc.demo.dao.jooq.Webgen;
import com.ysu.zyw.tc.demo.dao.jooq.tables.records.TUiPersonRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUiPerson extends TableImpl<TUiPersonRecord> {

    private static final long serialVersionUID = 496151428;

    /**
     * The reference instance of <code>webgen.T_UI_PERSON</code>
     */
    public static final TUiPerson T_UI_PERSON = new TUiPerson();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUiPersonRecord> getRecordType() {
        return TUiPersonRecord.class;
    }

    /**
     * The column <code>webgen.T_UI_PERSON.PK_CLASS</code>.
     */
    public final TableField<TUiPersonRecord, Long> PK_CLASS = createField("PK_CLASS", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>webgen.T_UI_PERSON.PK_PERSON</code>.
     */
    public final TableField<TUiPersonRecord, Long> PK_PERSON = createField("PK_PERSON", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>webgen.T_UI_PERSON.DEMO_INT</code>.
     */
    public final TableField<TUiPersonRecord, Integer> DEMO_INT = createField("DEMO_INT", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>webgen.T_UI_PERSON.DEMO_LONG</code>.
     */
    public final TableField<TUiPersonRecord, Long> DEMO_LONG = createField("DEMO_LONG", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>webgen.T_UI_PERSON.DEMO_BIGDIMAL</code>.
     */
    public final TableField<TUiPersonRecord, BigDecimal> DEMO_BIGDIMAL = createField("DEMO_BIGDIMAL", org.jooq.impl.SQLDataType.DECIMAL.precision(6, 2), this, "");

    /**
     * The column <code>webgen.T_UI_PERSON.DEMO_STRING</code>.
     */
    public final TableField<TUiPersonRecord, String> DEMO_STRING = createField("DEMO_STRING", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

    /**
     * The column <code>webgen.T_UI_PERSON.DEMO_BOOLEAN</code>.
     */
    public final TableField<TUiPersonRecord, Boolean> DEMO_BOOLEAN = createField("DEMO_BOOLEAN", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>webgen.T_UI_PERSON.DEMO_TIMESTAMP</code>.
     */
    public final TableField<TUiPersonRecord, Timestamp> DEMO_TIMESTAMP = createField("DEMO_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>webgen.T_UI_PERSON</code> table reference
     */
    public TUiPerson() {
        this("T_UI_PERSON", null);
    }

    /**
     * Create an aliased <code>webgen.T_UI_PERSON</code> table reference
     */
    public TUiPerson(String alias) {
        this(alias, T_UI_PERSON);
    }

    private TUiPerson(String alias, Table<TUiPersonRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUiPerson(String alias, Table<TUiPersonRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Webgen.WEBGEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TUiPersonRecord> getPrimaryKey() {
        return Keys.KEY_T_UI_PERSON_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TUiPersonRecord>> getKeys() {
        return Arrays.<UniqueKey<TUiPersonRecord>>asList(Keys.KEY_T_UI_PERSON_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUiPerson as(String alias) {
        return new TUiPerson(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUiPerson rename(String name) {
        return new TUiPerson(name, null);
    }
}
