/*
 * This file is generated by jOOQ.
*/
package com.ysu.zyw.tc.demo.dao.jooq;


import com.ysu.zyw.tc.demo.dao.jooq.tables.TUiClass;
import com.ysu.zyw.tc.demo.dao.jooq.tables.TUiPerson;
import com.ysu.zyw.tc.demo.dao.jooq.tables.records.TUiClassRecord;
import com.ysu.zyw.tc.demo.dao.jooq.tables.records.TUiPersonRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>webgen</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TUiClassRecord> KEY_T_UI_CLASS_PRIMARY = UniqueKeys0.KEY_T_UI_CLASS_PRIMARY;
    public static final UniqueKey<TUiPersonRecord> KEY_T_UI_PERSON_PRIMARY = UniqueKeys0.KEY_T_UI_PERSON_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TUiClassRecord> KEY_T_UI_CLASS_PRIMARY = createUniqueKey(TUiClass.T_UI_CLASS, "KEY_T_UI_CLASS_PRIMARY", TUiClass.T_UI_CLASS.PK_CLASS);
        public static final UniqueKey<TUiPersonRecord> KEY_T_UI_PERSON_PRIMARY = createUniqueKey(TUiPerson.T_UI_PERSON, "KEY_T_UI_PERSON_PRIMARY", TUiPerson.T_UI_PERSON.PK_CLASS, TUiPerson.T_UI_PERSON.PK_PERSON);
    }
}
