/*
 * This file is generated by jOOQ.
*/
package com.ysu.zyw.tc.demo.dao.jooq;


import com.ysu.zyw.tc.demo.dao.jooq.tables.TUiClass;
import com.ysu.zyw.tc.demo.dao.jooq.tables.TUiPerson;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in webgen
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>webgen.T_UI_CLASS</code>.
     */
    public static final TUiClass T_UI_CLASS = com.ysu.zyw.tc.demo.dao.jooq.tables.TUiClass.T_UI_CLASS;

    /**
     * The table <code>webgen.T_UI_PERSON</code>.
     */
    public static final TUiPerson T_UI_PERSON = com.ysu.zyw.tc.demo.dao.jooq.tables.TUiPerson.T_UI_PERSON;
}
