/*
 * This file is generated by jOOQ.
*/
package com.ysu.zyw.tc.demo.dao.jooq;


import com.ysu.zyw.tc.demo.dao.jooq.tables.TUiClass;
import com.ysu.zyw.tc.demo.dao.jooq.tables.TUiPerson;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Webgen extends SchemaImpl {

    private static final long serialVersionUID = 49759025;

    /**
     * The reference instance of <code>webgen</code>
     */
    public static final Webgen WEBGEN = new Webgen();

    /**
     * The table <code>webgen.T_UI_CLASS</code>.
     */
    public final TUiClass T_UI_CLASS = com.ysu.zyw.tc.demo.dao.jooq.tables.TUiClass.T_UI_CLASS;

    /**
     * The table <code>webgen.T_UI_PERSON</code>.
     */
    public final TUiPerson T_UI_PERSON = com.ysu.zyw.tc.demo.dao.jooq.tables.TUiPerson.T_UI_PERSON;

    /**
     * No further instances allowed
     */
    private Webgen() {
        super("webgen", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TUiClass.T_UI_CLASS,
            TUiPerson.T_UI_PERSON);
    }
}
