CREATE TABLE T_UI_CLASS (
  PK_CLASS       BIGINT(16) PRIMARY KEY,
  DEMO_INT       INT,
  DEMO_LONG      BIGINT(16),
  DEMO_BIGDIMAL  NUMERIC(6, 2),
  DEMO_STRING    VARCHAR(16),
  DEMO_BOOLEAN   TINYINT,
  DEMO_TIMESTAMP TIMESTAMP
);

CREATE TABLE T_UI_PERSON (
  PK_CLASS       BIGINT(16) ,
  PK_PERSON      BIGINT(16),
  DEMO_INT       INT,
  DEMO_LONG      BIGINT(16),
  DEMO_BIGDIMAL  NUMERIC(6, 2),
  DEMO_STRING    VARCHAR(16),
  DEMO_BOOLEAN   TINYINT,
  DEMO_TIMESTAMP TIMESTAMP,
  PRIMARY KEY (PK_CLASS, PK_PERSON)
);